### PR TITLE
Updated ControlNet-with-Inpaint-Demo-colab.ipynb with diffusers==0.29.0 and changed HEDdetector pretrained model

### PR DESCRIPTION
**Pull request by SahilCarterr**
PR for Updated ControlNet-with-Inpaint-Demo.colab.ipynb
-----------------------------------------------------------------

**Description:**

This pull request updates the `ControlNet-with-Inpaint-Demo.colab.ipynb` notebook with the following changes:

-   Upgrades the `diffusers` library to version 0.29.0.
-   Modifies the pre-trained model used by `HEDdetector` for edge detection. ( `lllyasviel/Annotators`)

**Detailed changes:**

-   In the cell where `diffusers` is installed, update the version to `0.29.0`:

```
!pip install diffusers==0.29.0

```

-   In the cell where `HEDdetector` is loaded, update the pre-trained model name:

```
hed_detector = HEDdetector.from_pretrained("lllyasviel/Annotators") 

```

**Testing:**

I have tested these changes locally and the notebook runs successfully Notebook with images [here](https://nbviewer.org/github/SahilCarterr/Impainting-Diffusers/blob/57977eb5f7602c8c5b5b0ee991c3870d5f91fb73/Control%20Net/Copy_of_ControlNet_with_Inpaint_Demo_colab_with_Images.ipynb) 

**Please review these changes and merge them if approved.**

**Thanks,**

### CODE REVIEW

**Comment by mikonvergence** [comment]
Hi @SahilCarterr - thanks for the update, good work!

A few comments:
* Ideally the standard non-colab notebook [ControlNet-with-Inpaint-Demo.ipynb](https://github.com/mikonvergence/ControlNetInpaint/blob/main/ControlNet-with-Inpaint-Demo.ipynb) should get updated too
* It seems more work needs to be done to make it compatible with diffusers `0.29.0`, currently importing the main pipeline results in `ModuleNotFoundError: No module named 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_controlnet'`, so a few more fixes are needed. I can do this later, or maybe you would like to?

**Comment by SahilCarterr** [comment]
Hello @mikonvergence i have updated the `ControlNet-with-Inpaint-Demo.ipynb` to run on local machine and fixed  import errors in `ControlNet-with-Inpaint-Demo-colab.ipynb`

**Comment by SahilCarterr** [comment]
@mikonvergence

**Comment by mikonvergence** [comment]
Hi, this repo contains a custom solution for `StableDiffusionControlNetInpaintPipeline` that was created and published before a similar solution was incorporated into `diffusers`. For the sake of the record, and the fact that the implementations are somewhat different, I never deleted the repo and its purpose is still the same, which is an independent implementation of the pipeline.

Hence, importing the object from the main library defeats the whole purpose of this repo:
```python
from diffusers import StableDiffusionControlNetInpaintPipeline  ####changed-----
```

I cannot merge if the changes simply bypass the entire source code in `src/`, sorry! Thanks for the input!

**Pull request closed without merging**
