### PR TITLE
Fix support for diffusers 0.15.0

### PR DESCRIPTION
**Pull request by remorses**
To support latest diffusers you also need to wait for this [PR](https://github.com/huggingface/diffusers/pull/3118)

### CODE REVIEW

**Comment by mikonvergence** [comment]
Yeah, I just realised the positional arg `do_classifier_free_guidance` is also causing problems with the latest release.

Let's see if that can be fixed in the PR you mentioned on the diffusers side. If it doesn't get resolved in the next week or so, we can adjust the code in this repo.

For now, I will make it explicit that `diffusers==0.14.0` is currently supported.

**Comment by mikonvergence** [comment]
@remorses It seems that the issue does not occur with `0.16.0`? Is it okay to close this down?

**Comment by remorses** [comment]
I would merge this PR because direct use of model parameters is discouraged, it’s better to use the config object 

feel free to close the PR if you don’t want to

**Comment by mikonvergence** [comment]
Right, there is that too. I agree, will merge it then.

**Pull request merged**
